
services:
  postgres-db:
    image: postgres:17
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zwJrSJtbPaHJRbvdbJEMXKAxYWmqksAG
  backend:
    build: ./backend
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vite-app
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
