
services:
  postgres-db:
    image: postgres:17
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zwJrSJtbPaHJRbvdbJEMXKAxYWmqksAG
  spring-app:
    image: backend-escolawilliams:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL:jdbc:postgresql://interchange.proxy.rlwy.net:44573/railway
    depends_on:
      - postgres-db

  spa-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - spring-app
 