
services:
  postgres-db:
    image: postgres:17
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zwJrSJtbPaHJRbvdbJEMXKAxYWmqksAG
  springboot:
    build: ./backend
    container_name: springboot-app
    restart: always
    ports:
      - "9090:9090"
    networks:
      - app-network

  react:
    build: ./frontend
    container_name: react-app
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot
      - react
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
